apiVersion: v1
kind: ConfigMap
metadata:
  name: variantautoscaling-config
  namespace: inferno-autoscaler-system
  labels:
    app.kubernetes.io/name: inferno-autoscaler
    app.kubernetes.io/managed-by: kustomize
data:
  # Prometheus configuration
  PROMETHEUS_BASE_URL: "http://kube-prometheus-stack-prometheus.inferno-autoscaler-monitoring.svc.cluster.local:9090"
  
  # Optimization configuration
  GLOBAL_OPT_INTERVAL: "60s"
  GLOBAL_OPT_TRIGGER: "false"
  
  # Optimizer engine configuration
  INFERNO_OPTIMIZER_TYPE: "go"
  INFERNO_PYTHON_PATH: "python3"
  INFERNO_PYTHON_SCRIPT: "autoscaler/cmd_folder/go_autoscaler_wrapper.py"
  INFERNO_WORKING_DIR: "/tmp" 