apiVersion: llmd.ai/v1alpha1
# Optimizing a variant, create only when the model is deployed and serving traffic
# this is for the collector the collect existing (previous) running metrics of the variant.
kind: VariantAutoscaling
metadata:
  # Unique name of the variant
  name: vllme-deployment 
  namespace: llm-d-sim
  labels:
    inference.optimization/acceleratorName: A100
# This is essentially static input to the optimizer
spec:
  # OpenAI API compatible name of the model
  modelID: default/default
  # Add SLOs in configmap, add reference to this per model data
  # to avoid duplication and Move to ISOs when available
  sloClassRef:
    # Configmap name to load in the same namespace as optimizer object
    # we start with static (non-changing) ConfigMaps (for ease of implementation only)
    name: premium
    # Key (modelID) present inside configmap
    key: opt-125m
  # Static profiled benchmarked data for a variant running on different accelerators
  modelProfile:
    accelerators:
      - acc: "A100"
        accCount: 1
        alpha: "20.58"
        beta: "0.41"
        maxBatchSize: 4
        atTokens: 128
      - acc: "MI300X"
        accCount: 1
        alpha: "7.77"
        beta: "0.15"
        maxBatchSize: 4
        atTokens: 128
      - acc: "G2"
        accCount: 1
        alpha: "17.15"
        beta: "0.34"
        maxBatchSize: 4
        atTokens: 128
