apiVersion: llmd.ai/v1alpha1
# Optimizing a variant, create only when the model is deployed and serving traffic
# this is for the collector the collect existing (previous) running metrics of the variant.
kind: VariantAutoscaling
metadata:
  # Unique name of the variant
  name: vllme-deployment 
  namespace: llm-d-sim
  labels:
    inference.optimization/acceleratorName: A100
# This is essentially static input to the optimizer
spec:
    # OpenAI API compatible name of the model
  modelID: default/default
  # Reference to service class configuration deployed with Inferno
  sloClassRef:
    name: service-classes-config
    key: premium.yaml
  # Static profiled benchmarked data for a variant running on different accelerators
  modelProfile:
    accelerators:
      - acc: "A100"
        accCount: 1
        alpha: "20.58"
        beta: "0.41"
        maxBatchSize: 4
